### ISSUE TITLE
Question sur la connexion ssh

### ISSUE THREAD

**Issue by redDwarf03** [TheStaticTurtle/DemoArenaMobile-Flutter#1]
Salut

Je voudrais faire une connexion à un vps avec un tunnel
Ma commande sur putty est 

-L 9999:localhost:9009 root@123.456.127.18 -pw password1!

Aurais tu une idée vu que tu as implémenté une méthode ssh. Merci!

**Comment by Dastan21** [comment]
Google est ton meilleur ami !

**Comment by redDwarf03** [comment]
Pas dans ce cas là malheureusement ...

**Comment by Dastan21** [comment]
Je troll évidemment 😉

**Comment by TheStaticTurtle** [comment]
Voici le module que j'utilise, il me semble qu'il a tout les binds de JSCH (module ssh sur android) peut faire un tunnel remote et local (pas dynamique) https://pub.dev/packages/ssh . J'avais test de faire un tunnel mais j'ai plus se bout de code sry.
Maintenant pti cour github en avance les issue c'est pas fait pour sa ;)
