### ISSUE TITLE
PlatformException(error, Unsupported value:)

### ISSUE THREAD

**Issue by bsachart** [TheStaticTurtle/DemoArenaMobile-Flutter#2]
**Bug:**
Affichage d'un message d'erreur lors du lancement de l'application Demo Arena depuis le début de la deuxième moitié de l'année sans raison particulière.

**Screenshots:**
![Screenshot_20210311-192208](https://user-images.githubusercontent.com/59805909/110836373-3f1a5280-82a0-11eb-82d3-9066f44c1f2f.jpg)

**Smartphone:**
 - Device: Samsung Galaxy A8 (2018)
 - OS: Android
 - Version Android: 9
 - Version One UI: 1

**Additional context:**
Application désinstallée et réinstallée plusieurs fois depuis l'apk, sans succès.
Semble être le seul de mon group de TP à avoir ce problème.

**Comment by TheStaticTurtle** [comment]
Fixed with last commit (55cef7daeccca8a12b980d79432fbfbaa8c9e3a8)
